### ISSUE TITLE
More flexible way of providing days off

### ISSUE THREAD

**Issue by hopsor** [diacode/holidays#11]
We are considering using the project in Bizneo to manage the holidays of the whole team but with current implementation of days off I think is not possible for us since we have different cases with different days off and having a yearly fixed amount of them before hand in `config/available_vacations.yml` is a problem. For instance I've joined the company in September so my amount of days off should be proportional to what it's set in `config/available_vacations.yml`.

To make it the most flexible way possible I'd remove `config/available_vacations.yml` and give admins the responsability of giving the days off to the users. The vacation request would work in the same way but the calculation of available days would be based on the amount of days off you have been granted.

It might sound like something that would give a lot of work to the admin however I suggest developing a user interface for them where they could grant an amount of days to a selection of users in just one action. 

What do you think @javiercr ?

**Comment by javiercr** [comment]
I think that would be ideal!

**Comment by hopsor** [comment]
will work on that then
