### ISSUE TITLE
Replace gravatar with image uploading

### ISSUE THREAD

**Issue by hopsor** [diacode/holidays#17]
Gravatar for big teams is not very suitable since you force all the people signing up there. It'll be more convenient having the ability of uploading your avatar with Carrierwave to S3 or somewhere else.

**Comment by dgdavid** [comment]
@hopsor, you also could take a look or take in account the [Refile](https://github.com/refile/refile) and [Shrine](https://github.com/janko-m/shrine) gems.

**Comment by hopsor** [comment]
thanks @dgdavid! I'll take a look to these two as well. Haven't used them before
