### ISSUE TITLE
Sign out link doesn't work

### ISSUE THREAD

**Issue by hopsor** [diacode/holidays#5]
Sign out link doesn't work.

Problem is in this block which is preventing the children link from doing the its http call.

https://github.com/diacode/holidays/blob/master/app/frontend/javascripts/widgets/user_nav.coffee#L10

**Comment by bigardone** [comment]
Fixed in:
https://github.com/diacode/holidays/commit/82f648f7d778624bf0ea233b459b0d5152a48a15
https://github.com/diacode/holidays/commit/dd16be639b45276deb9afc40ce52933bc0ced8fc
